### PR TITLE
andes datepicker color accent

### PR DESCRIPTION
**Pull request by AdrianDeSeta1985**
## Useful links
- [Contributing](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CONTRIBUTING.md) has more information and tips for a great pull request. This will give you a nice introduction about how to contribute with Andes.
- [Wiki](https://github.com/mercadolibre/fury_andesui-android/wiki) has all the info you need to start with Andes. Even I heard there's a video there...

## Motivation
obtaining the color resources of ML and MP

## Description
datepicker styles have been modified so that it automatically takes the colors of MP and ML

Try to answer those questions:
- What is it about?
- How does it work?

## Affected component
affects the "accent" colors in the datepicker

## Frontify component link
The UX team behind Andes keeps all the Andes Components inside the Frontify site. Each component has its own section. Let us know the section of the component you want to modify.

## Screenshots
This is a UI library, delight us with some stunning images.

## Checks
Are you sure you followed all those steps? In such case, let's say with me "I solemnly declare that ...":
- [ ] I have coded an example inside the Demo App,
- [ ] I have added proper tests,
- [x] I have modified the [Changelog](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CHANGELOG.md) file,
- [ ] I have updated GitHub wiki,
- [ ] I have the explicit approval of one or more members of the UX Team,
- [ ] I have updated the version in gradle.properties file.

## Change type
This is easy, let us know what this code is about:
- [ ] This code adds a new component
- [x] This code includes improvements to an existent component
- [ ] This code improves or modifies ONLY the Demo App.

## Check common errors
Whether you are an Android or iOS developer and if you're still there then we'll give you a present:
https://proandroiddev.com/how-to-maximize-androids-ui-reusability-5-common-mistakes-cb2571216a9f

### CODE REVIEW

**Review by snti — DISMISSED** [review]

**Comment by eportasML** [comment]
@AdrianDeSeta1985 te acutalizas el changelog? Esta en una version anterior a la nueva. También si podes completa el template del PR donde aplique 🙏

**Review by eportasML — APPROVED** [review]

**Comment by joalonsopint** [comment]
@AdrianDeSeta1985 podrías colocar unos screenshots?, así nos das una ayuda visual ;)

**Comment by AdrianDeSeta1985** [comment]
> @AdrianDeSeta1985 podrías colocar unos screenshots?, así nos das una ayuda visual ;)

image

**Comment by eportasML** [comment]
@AdrianDeSeta1985 te molesto de vuelta para q te actualices el branch y cambies el changelog / gradle.properties a 3.5.1 porque salio la 3.5.0 el lunes

**Pull request merged**
